pool:
  name: "Hosted Ubuntu 1604"

stages:

- stage: BuildAndDeployToTst
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
    - template: templates/azure_release_pipeline.yml
      parameters:
        Environment: Tst
        # VariableGroup: MART-ACC
        # project_name: $(project_name)

- stage: BuildAndDeployToAcc
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: templates/azure_release_pipeline.yml
      parameters:
        Environment: Acc

- stage: BuildAndDeployToPrd
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: templates/azure_release_pipeline.yml
      parameters:
        Environment: Prd


