resources:
  repositories:
  - repository: Test
    type: GitHub
    source: marlinknl/mart-dbs
    pr: 
      branches:
      - master
      - develop

    
stages:
- stage: Build
  jobs:
    - template: templates/build.yml

- stage: ReleaseToTest
  dependsOn: Build
  jobs:
    - template: templates/release.yml
      parameters: 
        Environment: Tst
        VariableGroup: MART-ACC

- stage: ReleaseToAcceptance
  dependsOn: ReleaseToTest
  jobs:
    - template: templates/release.yml
      parameters: 
        Environment: Acc
        VariableGroup: MART-ACC

- stage: ReleaseToProduction
  dependsOn: ReleaseToAcceptance
  jobs:
    - template: templates/release.yml
      parameters: 
        Environment: Prd
        VariableGroup: MART-PRD
