trigger:
  batch: true
  branches:
    include: 
    - master
    - vnext

pool:
  name: "Hosted Ubuntu 1604"

steps:
- script: python3 ci_cd/build_release.py
  workingDirectory: $(Build.SourcesDirectory)
  continueOnError: true