trigger:
  batch: true
  branches:
    include: 
    - develop
    - vnext
    exclude:
    - master

pool:
  name: "Hosted Ubuntu 1604"

steps:
# - script: python3 ci_cd/build_release.py
#   workingDirectory: $(Build.SourcesDirectory)
#   continueOnError: true

# - ${{ if and(ne(project_name, ''), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
- template: templates/azure_release_pipeline.yml
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  # parameters:
    # Environment: Tst
    # VariableGroup: MART-ACC
    # project_name: $(project_name)
